trigger:
  - main

pool:
  {{POOL OPTIONS HERE}}

jobs:
  - job: Prepare_Config
    displayName: 'Archive and Publish Config Snapshot'
    steps:
      - powershell: |
          Get-ChildItem -Path config -Filter *.json | Where-Object { $_.Name -notlike '*.flattened.json' } | ForEach-Object {
            $json = Get-Content $_.FullName | ConvertFrom-Json
            $flat = @{}
            foreach ($key in $json.PSObject.Properties.Name) {
              $value = $json.$key
              if ($value -is [System.Collections.IEnumerable] -and !$value.GetType().IsPrimitive -and $value.GetType().Name -ne 'String') {
                $flat[$key] = $value | ConvertTo-Json -Compress
              } elseif ($value -is [PSCustomObject]) {
                $flat[$key] = $value | ConvertTo-Json -Compress
              } else {
                $flat[$key] = $value
              }
            }
            $flattenedPath = "config/$($_.BaseName).flattened.json"
            $flat | ConvertTo-Json -Compress | Set-Content $flattenedPath
          }
        displayName: 'Flatten all config JSON files'

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: 'config'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'config'
          ArtifactName: 'flattened-configs'
          publishLocation: 'Container'

  - job: Deploy_Dev
    displayName: 'Deploy to Dev'
    dependsOn: Prepare_Config
    pool: 
      {{POOL OPTIONS HERE}}
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'flattened-configs'
          downloadPath: '$(Pipeline.Workspace)'
      - template: deploy-template.yaml
        parameters:
          environment: 'dev'
          configFile: 'config/dev.json'
          flattenedFile: '$(Pipeline.Workspace)/flattened-configs/dev.flattened.json'
          appConfigEndpoint: '{{APP CONFIG HERE}}'
          azureSubscription: '{{AZURE SUBSCRIPTION HERE}}'