trigger:
  - main

pool:
  {{POOL OPTIONS HERE}}

jobs:
  - job: Prepare_Config
    displayName: 'Prepare Configuration Files'
    steps:
      - template: prepare-template.yaml
    

  - job: Deploy_Dev
    displayName: 'Deploy to Dev'
    dependsOn: Prepare_Config
    pool: 
      {{POOL OPTIONS HERE}}
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'flattened-configs'
          downloadPath: '$(Pipeline.Workspace)'
      - template: deploy-template.yaml
        parameters:
          environment: 'dev'
          configFile: 'config/dev.kv.json'
          flattenedFile: '$(Pipeline.Workspace)/flattened-configs/dev.kv.json'
          appConfigEndpoint: '{{APP CONFIG HERE}}'
          azureSubscription: '{{AZURE SUBSCRIPTION HERE}}'